### ISSUE TITLE
Clipboard import of text fields

### ISSUE THREAD

**Issue by charlesknightsbridge** [EpiData-dk/analysis#78]
Request from JL:
Should text fields be imported as UPPER (currently) or as normal string fields?
I cannot reproduce this behaviour.

### Example

spreadsheet:
![image](https://github.com/EpiData-dk/analysis/assets/855040/ccc2df75-9708-4aea-9511-eaa0b59494b5)

analysis:
```
.read !cb;
Lines: 2
Separators: (Tab: 3) (Semicolon: 0) (Comma: 0) (Space: 0) 
Separator found: 	
Loaded file: /Applications/EpiStats/(Not Saved)
Cycle: 0 Datasets: 1 Modified: 2024-05-20 8:22:06 AM 

.list v;
 Name Type    Length Decimal Label Valuelabels Missing
 vara Integer 2      0       vara                     
 varb String  4      0       varb                     
 varc String  4      0       varc                     
 vard String  4      0       vard                     

.list data;
 Obs. No vara varb varc vard
 1       13   ABCD abcd Abcd
 2       14   abcd abcd abcd
```

**Comment by torstenchr** [comment]
@charlesknightsbridge , @JLepidata 
The cvs detection algorithm only assigns a filed the UPPERCASE type if and only if all records in a fields are found to be complete uppercase text. 

And to be clear - the comment in the code states the following order of found type. So if a text field has only uppercase characters it has a higher preferred type than that of a "normal" string field. And last, if the string field has more than 70 character it is considered to be a memo field.
  //  1: Bool
  //  2: Int
  //  3: Float
  //  3: Date/Time
  //  4: Uppercase
  //  5: String
  //  6: Memo

**Comment by JLepidata** [comment]
I suggest to remove the upper string . It gives me problems. 

Typically since we have data with 12 characters and mostly numerical, except for say 1 or two out of 500 with 11 Gita and one letter, 
E.g.
1234567890123L
Could also be an option 
!String. Or. !Nou 
Bw Jens 

Another option is to allow during merge that
File a with a string field could be merged with upper from file b

Read a;
Merge v1 !fn:="b";  
// allow this if v1 is string in a and upper in b

Bw Jens 



⁣Hent BlueMail til Android ​

Den 29. maj 2024 19.18, fra 19.18, Torsten Bonde Christiansen ***@***.***> skrev:

**Comment by torstenchr** [comment]
I now that we have discussed this subject a number of times on previous occasions. The requirements seem to change based on the current project so maybe we should consider making a bigger chance.

Something like providing a better means of setting the import options on a broader scale. Like what each individual field should be imported as, no matter the auto detected types?

It is a bigger task and will require some time remodeling, but it will give our users more flexibility in the end.

**Comment by JLepidata** [comment]
The current symptom is not new. The upper versus string in append or merge always created difficulties. But a complete rewrite of "read !cb” is currently overkill. 

If looking at main problems we are having now and therefore switch to Stats or R or Classic EpiData are:

Getting our very efficient output into a pdf or html page in Analysis , e.g. the type command.

Spc graphs

Peculiar merge and append problems like the mentioned. But also errors I could not replicate. But possibly related to epx with multiple datasets due to the append not working always . We need append to ensure proper entry, since any merge will change coordinates of fields.



Best wishes 
Jens

⁣Hent BlueMail til Android ​

Den 29. maj 2024 22.39, fra 22.39, Torsten Bonde Christiansen ***@***.***> skrev:

**Comment by charlesknightsbridge** [comment]
I propose the following, since read !cb is meant to be a simple way to get data in. Does this also impact reading a text file or do we have all the options we need when importing from a text or csv file?I don’t think we have a way to change the type of a field, but it’s still pretty simple to define / assign /delete if anyone wants to.My proposal:- add an option to read (valid only with !cb or when reading text/csv)  !noucWhich will force normal string field type for all fields found to have text. The default action is what is done now.The discussion of how merge should work needs to be a separate issue.JamieOn May 29, 2024, at 4:39 PM, Torsten Bonde Christiansen ***@***.***> wrote:﻿
I now that we have discussed this subject a number of times on previous occasions. The requirements seem to change based on the current project so maybe we should consider making a bigger chance.
Something like providing a better means of setting the import options on a broader scale. Like what each individual field should be imported as, no matter the auto detected types?
It is a bigger task and will require some time remodeling, but it will give our users more flexibility in the end.

**Comment by JLepidata** [comment]
I agree, Jamie!

Fixing one issue is a good strategy!

Bw Jens 



⁣Hent BlueMail til Android ​

Den 29. maj 2024 22.55, fra 22.55, Jamie ***@***.***> skrev:

**Comment by torstenchr** [comment]
Just to be clear on this on - should we have an options **!nouc** that always creates the string field as "normal" string and not uppercase?
What do we do with strings longer than 70 characters, are they still considered memo fields?
